### ISSUE TITLE
Consider using queue interprop as abstraction for queues

### ISSUE THREAD

**Issue by makasim** [traderinteractive/mongo-queue-php#59]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

**Comment by chadicus** [comment]
@makasim  we are getting ready to release version 3 of the library which will move us closer to the interop class structure. As part of version 4 we will absolutely switch to the interop abstractions
