### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by jmaybury** [traderinteractive/mongo-queue-php#66]
This package cannot be installed under PHP 8. Composer complains:

> traderinteractive/mongo-queue v3.0.1 requires php ^7.0 -> your php version (8.1.11) does not satisfy that requirement.

If you go ahead and install it anyway with --ignore-platform-reqs, it appears to work for my particular use case at least, albeit with some warnings:

> PHP Warning:  Private methods cannot be final as they are never overridden by other classes in {...}/vendor/traderinteractive/mongo-queue/src/AbstractQueue.php on line 267
> PHP Warning:  Private methods cannot be final as they are never overridden by other classes in {...}/vendor/traderinteractive/mongo-queue/src/AbstractQueue.php on line 387

I have not attempted to run a full test suite to check for other potential compatibility issues.

**Comment by chrisryan** [comment]
Support for PHP 8 is now available in v4.0.0.
