### ISSUE TITLE
PHP 8.1 deprecation warnings

### ISSUE THREAD

**Issue by jmaybury** [traderinteractive/mongo-queue-php#69]
In PHP 8.1 with an error_reporting setting that includes E_DEPRECATED, messages like this appear in the error log:

> PHP Deprecated:  Implicit conversion from float 1676606463.41258 to int loses precision in /www/vendor/traderinteractive/mongo-queue/src/AbstractQueue.php on line 414

Rather than messing around creating a fork and a pull request for a simple change, I'll just say: changing the return type of `calculateEndTime` from int to float stops the messages, and appears to me to be an adequate solution.

**Comment by chrisryan** [comment]
Fix released in v4.0.1.
